"""
Stress Test + Monte Carlo — stress.py

Crisis shock profiles EXTRACTED FROM REAL HISTORICAL DATA but split into:
- EXOGENOUS variables (oil, labor force, productivity, tariffs) — applied as the shock
- POLICY variables (fed rate, spending, tax, M2) — EXCLUDED, let engine respond endogenously

This means the shock magnitudes are historically calibrated (real data) but the
policy response is generated by the engine's Taylor Rule + fiscal stabilizers,
not baked into the shock profile.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
import numpy as np
from data import DATASETS
from engine import simulate, SimResult


# ═══════════════════════════════════════════════════════════════
# EXOGENOUS vs POLICY classification
# ═══════════════════════════════════════════════════════════════

# Variables that CAUSE crises (extracted from history, applied as shocks)
EXOGENOUS_VARS = ["oilPrice", "laborForceGrowth", "productivityGrowth", "tariffRate"]

# Variables that are RESPONSES to crises (excluded from shock, engine generates them)
POLICY_VARS = ["fedRate", "govSpending", "taxRate", "moneySupplyGrowth"]


@dataclass
class ShockProfile:
    name: str
    description: str
    n_quarters: int
    source: str                     # which historical crisis this was extracted from
    exogenous_deltas: List[Dict[str, float]] = field(default_factory=list)
    # Also store what the historical policy response was, for reference
    historical_policy: List[Dict[str, float]] = field(default_factory=list)


def _extract_from_history(crisis_key: str, start_idx: int, end_idx: int,
                           label: str, desc: str) -> ShockProfile:
    """
    Extract exogenous shock deltas from real historical data.

    Only EXOGENOUS_VARS are included in the shock profile.
    POLICY_VARS are stored separately for reference but NOT applied.
    """
    ds = DATASETS[crisis_key]
    inputs = ds.inputs.to_dict("records")
    baseline = inputs[start_idx]
    n = min(end_idx + 1, len(inputs))

    exo_deltas = []
    pol_deltas = []
    for q in range(start_idx, n):
        exo = {v: round(inputs[q][v] - baseline[v], 3) for v in EXOGENOUS_VARS}
        pol = {v: round(inputs[q][v] - baseline[v], 3) for v in POLICY_VARS}
        exo_deltas.append(exo)
        pol_deltas.append(pol)

    return ShockProfile(
        name=label,
        description=desc,
        n_quarters=len(exo_deltas),
        source=f"{ds.label} (Q{start_idx+1}→Q{n})",
        exogenous_deltas=exo_deltas,
        historical_policy=pol_deltas,
    )


# ═══════════════════════════════════════════════════════════════
# PRE-BUILT PROFILES (extracted from real data)
# ═══════════════════════════════════════════════════════════════

SHOCK_CONFIGS = {
    "gfc": {
        "key": "gfc", "start": 3, "end": 11,
        "label": "🏠 GFC / Credit Crisis (2007–09)",
        "desc": "Historically calibrated from Q4 2007→Q4 2009. Oil spikes then crashes, "
                "labor force collapses -2.5%, productivity drops. "
                "Fed/fiscal response is endogenous (not baked in).",
    },
    "gulfwar": {
        "key": "gulfwar", "start": 6, "end": 11,
        "label": "🛢️ Oil Shock / Gulf War (1990–91)",
        "desc": "Historically calibrated from Q3 1990→Q4 1991. Oil spike +$7/bbl then reversal, "
                "labor force contracts mildly. Relatively mild shock.",
    },
    "dotcom": {
        "key": "dotcom", "start": 4, "end": 11,
        "label": "💻 Tech Bust / 9-11 (2001–02)",
        "desc": "Historically calibrated from Q1 2001→Q4 2002. Oil drops, labor force contracts -1%, "
                "productivity initially falls then recovers. Demand shock.",
    },
    "covid": {
        "key": "modern", "start": 20, "end": 23,
        "label": "🦠 COVID Pandemic (2020)",
        "desc": "Historically calibrated from Q1 2020→Q4 2020. Extreme labor collapse -5.5% in one quarter, "
                "oil crashes -$18, productivity spikes (remote work). Most severe acute shock in dataset.",
    },
    "volcker": {
        "key": "volcker", "start": 3, "end": 15,
        "label": "📈 Volcker Stagflation (1979–82)",
        "desc": "Historically calibrated from Q4 1979→Q4 1982. Sustained oil elevation, "
                "labor force contracting -2.5% by trough. Long 12-quarter shock.",
    },
}

# Also keep some hand-crafted hypothetical shocks that don't have direct historical parallels
HYPOTHETICAL_CONFIGS = {
    "trade_war": ShockProfile(
        name="🛃 Trade War Escalation (hypothetical)",
        description="Tariffs surge 25pp over 8 quarters. No direct historical parallel at this scale. "
                    "Hand-crafted based on 2018-19 US-China trade war pattern, amplified.",
        n_quarters=8, source="Hand-crafted (based on 2018-19)",
        exogenous_deltas=[
            {"oilPrice": 0, "laborForceGrowth": 0, "productivityGrowth": 0, "tariffRate": 5},
            {"oilPrice": 5, "laborForceGrowth": -0.1, "productivityGrowth": -0.2, "tariffRate": 12},
            {"oilPrice": 10, "laborForceGrowth": -0.2, "productivityGrowth": -0.5, "tariffRate": 20},
            {"oilPrice": 15, "laborForceGrowth": -0.3, "productivityGrowth": -0.8, "tariffRate": 25},
            {"oilPrice": 10, "laborForceGrowth": -0.2, "productivityGrowth": -0.6, "tariffRate": 25},
            {"oilPrice": 5, "laborForceGrowth": -0.1, "productivityGrowth": -0.4, "tariffRate": 20},
            {"oilPrice": 0, "laborForceGrowth": 0, "productivityGrowth": -0.2, "tariffRate": 15},
            {"oilPrice": 0, "laborForceGrowth": 0, "productivityGrowth": 0, "tariffRate": 10},
        ],
    ),
    "stagflation": ShockProfile(
        name="📉 Stagflation (hypothetical)",
        description="Combined oil shock + productivity collapse. Hand-crafted worst-case supply shock.",
        n_quarters=8, source="Hand-crafted",
        exogenous_deltas=[
            {"oilPrice": 10, "laborForceGrowth": 0, "productivityGrowth": 0, "tariffRate": 3},
            {"oilPrice": 25, "laborForceGrowth": -0.2, "productivityGrowth": -0.5, "tariffRate": 8},
            {"oilPrice": 40, "laborForceGrowth": -0.5, "productivityGrowth": -1.0, "tariffRate": 12},
            {"oilPrice": 50, "laborForceGrowth": -0.5, "productivityGrowth": -1.2, "tariffRate": 15},
            {"oilPrice": 45, "laborForceGrowth": -0.3, "productivityGrowth": -1.0, "tariffRate": 15},
            {"oilPrice": 35, "laborForceGrowth": -0.1, "productivityGrowth": -0.8, "tariffRate": 12},
            {"oilPrice": 25, "laborForceGrowth": 0, "productivityGrowth": -0.5, "tariffRate": 8},
            {"oilPrice": 15, "laborForceGrowth": 0, "productivityGrowth": -0.2, "tariffRate": 5},
        ],
    ),
}


def get_shock_profiles() -> Dict[str, ShockProfile]:
    """Build all shock profiles — historical extractions + hypotheticals."""
    profiles = {}
    for shock_id, cfg in SHOCK_CONFIGS.items():
        try:
            profiles[shock_id] = _extract_from_history(
                cfg["key"], cfg["start"], cfg["end"], cfg["label"], cfg["desc"])
        except Exception:
            pass
    profiles.update(HYPOTHETICAL_CONFIGS)
    return profiles


# ═══════════════════════════════════════════════════════════════
# SHOCK INJECTION
# ═══════════════════════════════════════════════════════════════

def apply_shock_to_params(
    base_params: dict,
    shock: ShockProfile,
    onset_quarter: int,
    severity: float = 1.0,
    n_total_quarters: int = 24,
) -> List[dict]:
    """
    Generate per-quarter input series by injecting EXOGENOUS shock deltas.
    Policy variables (fedRate, govSpending, taxRate, M2) stay at baseline —
    the engine's Taylor Rule and fiscal stabilizer handle the response.
    """
    series = []
    for q in range(n_total_quarters):
        pq = base_params.copy()
        pq["q"] = f"Q{q + 1}"
        shock_q = q - onset_quarter

        if 0 <= shock_q < shock.n_quarters:
            deltas = shock.exogenous_deltas[shock_q]
            for var, delta in deltas.items():
                if var in pq:
                    new_val = pq[var] + delta * severity
                    if var == "oilPrice":
                        new_val = max(10, new_val)
                    elif var == "tariffRate":
                        new_val = max(0, new_val)
                    pq[var] = round(new_val, 3)
        elif shock_q >= shock.n_quarters:
            # Post-shock recovery: 80%/quarter exponential decay toward baseline
            recovery_factor = 0.8 ** (shock_q - shock.n_quarters + 1)
            last_deltas = shock.exogenous_deltas[-1]
            for var, delta in last_deltas.items():
                if var in pq:
                    new_val = base_params[var] + delta * severity * recovery_factor
                    if var == "oilPrice":
                        new_val = max(10, new_val)
                    elif var == "tariffRate":
                        new_val = max(0, new_val)
                    pq[var] = round(new_val, 3)

        if "debtToGDP" not in pq:
            pq["debtToGDP"] = base_params.get("debtToGDP", 124)
        series.append(pq)

    return series


# ═══════════════════════════════════════════════════════════════
# MONTE CARLO SIMULATION
# ═══════════════════════════════════════════════════════════════

MC_NOISE_STD = {
    "fedRate": 0.15,
    "govSpending": 0.05,
    "taxRate": 0.2,
    "moneySupplyGrowth": 1.0,
    "tariffRate": 0.3,
    "oilPrice": 5.0,
    "laborForceGrowth": 0.15,
    "productivityGrowth": 0.3,
}


def monte_carlo_simulate(
    base_params: dict,
    initial_conditions: dict,
    n_sims: int = 200,
    n_quarters: int = 24,
    seed: int = 42,
) -> Dict[str, np.ndarray]:
    """Run Monte Carlo simulation with correlated random walk noise."""
    rng = np.random.RandomState(seed)
    output_keys = ["gdpGrowth", "inflation", "unemployment", "sp500Index",
                   "goldPrice", "bondYield10Y", "currencyIndex", "tradeBalance",
                   "wageGrowth", "consumerConfidence"]

    results_array = {k: np.zeros((n_quarters, n_sims)) for k in output_keys}

    for sim_i in range(n_sims):
        noisy_series = []
        for q in range(n_quarters):
            pq = base_params.copy()
            pq["q"] = f"Q{q + 1}"
            for param_key, std in MC_NOISE_STD.items():
                if param_key in pq:
                    noise = rng.normal(0, std)
                    if q > 0 and noisy_series:
                        prev_val = noisy_series[-1].get(param_key, pq[param_key])
                        noise = 0.7 * (prev_val - base_params[param_key]) + 0.3 * noise + rng.normal(0, std * 0.3)
                    new_val = pq[param_key] + noise
                    if param_key == "fedRate":
                        new_val = max(0, new_val)
                    elif param_key == "oilPrice":
                        new_val = max(20, new_val)
                    elif param_key in ("tariffRate", "govSpending"):
                        new_val = max(0, new_val)
                    pq[param_key] = new_val
            if "debtToGDP" not in pq:
                pq["debtToGDP"] = base_params.get("debtToGDP", 124)
            noisy_series.append(pq)

        sim_results = simulate(noisy_series[0], noisy_series, initial_conditions)
        for q_idx, r in enumerate(sim_results):
            for k in output_keys:
                results_array[k][q_idx, sim_i] = getattr(r, k)

    return results_array


def compute_percentiles(mc_results: Dict[str, np.ndarray],
                        pctiles: List[int] = [10, 50, 90]) -> Dict[str, Dict[int, np.ndarray]]:
    out = {}
    for k, arr in mc_results.items():
        out[k] = {p: np.percentile(arr, p, axis=1) for p in pctiles}
    return out
